name: ruleta
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  confetti: ^0.8.0
  flutter:
    sdk: flutter
  flutter_fortune_wheel: ^1.3.2
  shared_preferences: ^2.2.3
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
